config/routes.rb
Rails.application.routes.draw do

  get 'anand/index'

  get 'amit/index'

  get 'amit/new'

  devise_for :users
  resources :posts do
    resources :comments
  end

  resources :categories

root 'posts#index'

end

app/models/amit.rb
class Amit < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base

	validates :name, uniqueness: true

	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :category
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
	

	has_attached_file :image, styles: { medium: "900x500#", small: "350x200>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!
	before_action :find_category, only: [:show, :edit, :update, :destroy ]

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to categories_path
		else
			render action: :new
		end
	end

	def edit
		
	end

	def update
    	if @category.update_attributes(category_params)
	      	redirect_to categories_path
    	else
      		render action: :edit
    	end
  end

	def destroy
		if @category.destroy
      		redirect_to categories_path
    	end
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def find_category
		@category = Category.find(params[:id])		
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])	
		@comment = @post.comments.create(comment_params)

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

	

	private

	def comment_params
		params.require(:comment).permit(:name,:email, :body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:category].present?
      @category = Category.find_by(name: params[:category])
      @posts = Post.where(category_id: @category.id).order('created_at DESC')
    else  
  	 @posts = Post.all.order('created_at DESC')
    end
  end

  def new
    @post = Post.new
  end

  def create
  	@post = Post.new(params_post)
  	if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title,:body,:image,:color))
      redirect_to @post
    else  
      render ''
    end
  end

  def show
  	@post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def params_post
  	params.require(:post).permit(:title, :body, :image,:color, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def avatar_url(comment)
 		gravatar_id = Digest::MD5.hexdigest(comment.email.downcase)
    	"http://gravatar.com/avatar/#{gravatar_id}.png"
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<section id="post-833" class="quadro-mod type-blog clear blog-style-masonry masonry-margins-true ">
                <div class="inner-mod">
                <div class="blog-wrapper">
                <div id="grid" class="anim-grid anim-4 blog-container blog-content blog-masonry blog-columns-three">

                    <h2>Add New Category</h2>

                    <%= form_for [@category] do |f| %>
<p>
<%= f.label :category_name %><br>  
<%= f.text_field :name %>
</p>

<p>
<%= f.submit "Save" %>
</p>


<% end %>









                </div>
                </div>
                </div>
                </section>
               </section>

app/views/categories/edit.html.erb
    

   	<div class="container">
   	
	<div class="row">
		<%= link_to "Back", categories_path, :class => "btn btn-default" %>
	<div class="col-md-12" style="background-color: white; margin-top: 20px; padding: 30px;">
		<%= render 'form' %>
	</div>
	</div>
	</div>

app/views/categories/index.html.erb
<% @categories.each do |f| %>

<p>	<%= f.name %> | <%= link_to "Edit", edit_category_path(f) %> | <%= link_to "Delete", f, :confrm => "Are you sure?", :method => :delete %> </p> 
<%  end %>

app/views/categories/new.html.erb
	<div class="container">
	<div class="row">


	<div class="col-md-12" style="background-color: white; margin-top: 20px; margin-bottom: 20px; padding: 30px;">
		<%= render 'form' %>
		<%= link_to "Back", categories_path, :class => "btn btn-default" %>
	</div>
	</div>

	</div>

app/views/comments/_comment.html.erb
<div class="conmment">
<table>
	<tr>
		<td><%= image_tag avatar_url(comment) %></td>
		<td><p><strong><%= comment.name %></strong><br> <%= time_ago_in_words(comment.created_at) %> Ago</p></td>
	</tr>
</table>
	
	
	
	<p><%= comment.body %></p>
	
	<p>
		<%= link_to 'Delete' ,[comment.post, comment], method: :delete, data: {confirm: 'Are you sure?'} %>
	</p>
</div>

app/views/comments/_form.html.erb
<div class="container">
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
		<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit "Save" %>
	</p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HotShop Inside</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<link rel="alternate" type="application/rss+xml" title="Binder PRO &raquo; Blog Masonry, 3 Columns with margins Comments Feed" href="http://demos.quadroideas.com/binderpro/blog/blog-masonry-3-columns-with-margins/feed/" />
<link rel='stylesheet' id='contact-form-7-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=4.1' type='text/css' media='all' />
<link rel='stylesheet' id='crellyslider-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/crelly-slider/css/crellyslider.css?ver=0.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='woocommerce-layout-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css?ver=2.3.6' type='text/css' media='all' />
<link rel='stylesheet' id='woocommerce-smallscreen-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreen.css?ver=2.3.6' type='text/css' media='only screen and (max-width: 768px)' />
<link rel='stylesheet' id='woocommerce-general-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/woocommerce/assets/css/woocommerce.css?ver=2.3.6' type='text/css' media='all' />
<link rel='stylesheet' id='style-switcher-style-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/binderpro-switcher/style-switcher-styles.css?ver=4.1.1' type='text/css' media='all' />
<link rel='stylesheet' id='responsive-lightbox-nivo-front-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/responsive-lightbox/assets/nivo/nivo-lightbox.css?ver=4.1.1' type='text/css' media='all' />
<link rel='stylesheet' id='responsive-lightbox-nivo-front-template-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/responsive-lightbox/assets/nivo/themes/default/default.css?ver=4.1.1' type='text/css' media='all' />
<link rel='stylesheet' id='quadro-font-awesome-css'  href='//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css?ver=3.2.1' type='text/css' media='all' />
<link rel='stylesheet' id='quadro-page-builder-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/themes/binderpro/inc/qi-framework/plugins/page-builder-styles.css?ver=4.1.1' type='text/css' media='all' />
<link rel='stylesheet' id='quadro-crelly-slider-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/themes/binderpro/inc/qi-framework/plugins/crelly-slider-styles.css?ver=4.1.1' type='text/css' media='all' />

<link rel='stylesheet' id='woocommerce-styles-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/themes/binderpro/inc/woocommerce-styles.css?ver=4.1.1' type='text/css' media='all' />
<link rel='stylesheet' id='jetpack_css-css'  href='http://cdn.quadroideas.com/binderpro/wp-content/plugins/jetpack/css/jetpack.css?ver=3.3.3' type='text/css' media='all' />
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  
<script type='text/javascript' src='http://cdn.quadroideas.com/binderpro/wp-includes/js/jquery/jquery.js?ver=1.11.1'></script>
<script type='text/javascript' src='http://cdn.quadroideas.com/binderpro/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1'></script>
<script type='text/javascript' src='http://cdn.quadroideas.com/binderpro/wp-content/plugins/crelly-slider/js/jquery.crellyslider.min.js?ver=0.8.1'></script>
<script type='text/javascript' src='http://cdn.quadroideas.com/binderpro/wp-content/plugins/responsive-lightbox/assets/nivo/nivo-lightbox.min.js?ver=4.1.1'></script>
<script type='text/javascript'>var rlArgs={"script":"nivo","selector":"lightbox","custom_events":"","activeGalleries":"1","effect":"fade","clickOverlayToClose":"1","keyboardNav":"1","errorMessage":"The requested content cannot be loaded. Please try again later."};</script>

<script type='text/javascript' src='http://cdn.quadroideas.com/binderpro/wp-content/plugins/responsive-lightbox/js/front.js?ver=4.1.1'></script>
<script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js?ver=4.1.1'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://demos.quadroideas.com/binderpro/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://cdn.quadroideas.com/binderpro/wp-includes/wlwmanifest.xml" />

<meta name="generator" content="WordPress 4.1.1" />
<meta name="generator" content="WooCommerce 2.3.6" />
<link rel='canonical' href='http://demos.quadroideas.com/binderpro/blog/blog-masonry-3-columns-with-margins/' />
<link rel='shortlink' href='http://demos.quadroideas.com/binderpro/?p=839' />

<script type="text/javascript">var ajaxurl="http://demos.quadroideas.com/binderpro/wp-admin/admin-ajax.php"</script>
<script>WebFont.load({google:{families:['Droid+Serif:normal, bold','Roboto:300, normal, bold',],},timeout:3500});</script>


  <%= csrf_meta_tags %>


<style>

body{
  background-color:#eaeaea;
  font-family:"Roboto";
  font-size:18px
  }
.mod-title, .meta-nav strong, .site-header .widget-title, .static-menu .main-navigation .menu a{font-family:"Roboto"}.single-post article a, .single-post article a:visited,
.page-content a, .page-content a:visited{color:#BB5551}a:hover,
.single-post article a:hover,
.page-content a:hover{color:#231f20}h1 a, h2 a, h3 a, h4 a, h5 a, h6 a, h1, h2, h3, h4, h5, h6,
.mod-editor-content, .readmore-link, input[type="submit"], .comment-reply-link,
.comment-author cite, .post-navigation .meta-nav, .paging-navigation .meta-nav, .comment-navigation a,
blockquote, q, .taxonomy-description p, .wpcf7 p, .read-author-link a, .qbtn, input[type="button"],
.flashnews-content .entry-title, div#jp-relatedposts h3.jp-relatedposts-headline{font-family:"Droid Serif"}.woocommerce a.button, .woocommerce button.button, .woocommerce input.button, .woocommerce #respond input#submit,
.woocommerce #content input.button, .woocommerce-page a.button, .woocommerce-page button.button, .woocommerce-page input.button,
.woocommerce-page #respond input#submit, .woocommerce-page #content
input.button{font-family:"Droid Serif"}.main-navigation .menu
a{font-family:"Droid Serif"}.site-footer{background-color:#fff}.site-footer, .widget select, .widget input[type="submit"]{color:#}.site-footer
a{color:#}body{font-weight:300}.slider-nav-item
img{-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-o-user-select:none;user-select:none}.page-id-501{background:#fff}.page-id-501 .site-header{border-bottom:3px solid #000}.page-id-501 .quadro-mod{padding-top:15px;padding-bottom:15px}section#post-250{padding:0}section#post-588{padding:0
4%}section#post-569 .widget-area{background:#fafafa}section#post-566 .widget-area{border:3px
solid #000}.page-id-716 .display-back-img{filter:url("data:image/svg+xml;utf8,#grayscale");filter:gray;-webkit-filter:grayscale(100%)}@media only screen and (min-width: 1040px){.site-header-type2 .static-menu .main-navigation ul
li{padding:10px
25px 10px 0}}

</style>
</head>
<body class="page page-id-839 page-child parent-pageid-463 page-template page-template-template-modular page-template-template-modular-php site-header-type2 onsingle-fullwidth-right woo-sidebar-none woo-cols4 siteorigin-panels group-blog header-extras-on chrome">


       <style scoped>.page-header{background-color:#fff}</style>
          <div id="page" class="hfeed site"> 
          <%= render 'shared/header' %>


                    <%= yield %>
               
               
            <%= render 'shared/footer' %>   
            </div>  
          
</body>
</html>

app/views/posts/_form.html.erb
			<%= simple_form_for @post do |f| %>
				
				<% if @post.errors.any? %>
					<div id="errors">
						<h2><%= pluralize(@post.errors.count, "error")%>  prevented this post to save </h2>
						<ul>
							<% @post.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
				<p>
					Select the Category : <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a Category"} %>
			
					Select The Color : <%= f.select(:color, [['Red', '#bb5551'],
			                                  ['Blue', '#228c9b'],
			                                  ['Black', '#343434'],
			                                  ['Pink', '#B43F5A'],
			                                  ['Violet', '#4B1D37'],
			                                  ['Gray', '#C0C0B1'],
			                                  ['Blue2', '##9A2EFE'],
			                                  ['Orange', '##FA8258'],	
			                                  ['Dark', '#70575B']
			                                 ],{ :prompt => "Please select Color"}
			                                 ) %>
				</p>


				<p>
					<%= f.input :image %>
				</p>
				<p>
					<%= f.label :title %><br>
					<%= f.text_field :title %>
				</p>

				<p>
					<%= f.label :body %><br>
					<%= f.text_area :body %>
				</p>

				<p>
					<%= f.submit  "Save" %>
				</p>

			<% end %>

app/views/posts/edit.html.erb
	<div class="container">
	<div class="row">

	<div class="col-md-12" style="background-color: white; margin-top: 20px; padding: 30px;">
		<%= render 'form' %>
	</div>
	</div>
	</div>

app/views/posts/new.html.erb
	<div class="container">
	<div class="row">

	<div class="col-md-12" style="background-color: white; margin-top: 20px; padding: 30px;">
		<%= render 'form' %>
	</div>
	</div>
	</div>

app/views/posts/show.html.erb
<div id="content" class="site-content">
    <div id="primary" class="content-area"> 
        <main id="main" class="site-main" role="main">

            <article id="post-27" class="post-27 post type-post status-publish format-audio has-post-thumbnail hentry category-ideas category-news tag-tag2 tag-tag5 post_format-post-format-audio"> 
            <header class="entry-header clear">
                <h1 class="entry-title"><%= @post.title %></h1>
                <div class="entry-meta clear">
                <span class="posted-on">
                    <a href="http://demos.quadroideas.com/binderpro/2014/05/04/post-format-audio/" title="12:15 pm" rel="bookmark" >
                    <time class="entry-date published" datetime="2014-05-04T12:15:44+00:00"><%= @post.created_at.strftime("%B, %d, %Y") %> </time>
                    <time class="updated" datetime="2014-11-14T18:14:36+00:00">Nov 14, 2014</time></a>
                </span>
               
                <p class="cat-links">In <a href="http://demos.quadroideas.com/binderpro/category/ideas/" rel="category tag">Hotshop</a>, <a
                    href="http://demos.quadroideas.com/binderpro/category/news/" rel="category tag"><%= @post.category.name %></a>.
                </p>
                </div>
            </header>
            <div class="entry-thumbnail"> 
            <%= link_to image_tag(@post.image.url(:medium), :class => 'attachment-small-thumb wp-post-image')%>
            <!-- width="1400" height="480"-->
            </div>

            <div class="entry-content"> <!--[if lt IE 9]><script>document.createElement('audio');</script><![endif]--> 
           

            <p><%= @post.body %></p>
         

          
            <div class="sharedaddy sd-sharing-enabled">
                <div class="robots-nocontent sd-block sd-social sd-social-icon sd-sharing">
                    <h3 class="sd-title">Share this post</h3>
                    <%= social_share_button_tag(@post.title, :url => "http://128.199.206.209/posts/#{@post.id }") %>
                <di
            </div>
        </div>

        <div id='jp-relatedposts' class='jp-relatedposts' >
        </div>
    </div>

    <div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'blogkattilath';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

  
    </article>

    

    
    </main>
        </div>
                </div>

app/views/shared/_header.html.erb
<header id="masthead" class="site-header static-menu header-layout1 show-search" role="banner">
<div class="inner-header">
<div class="site-branding">
	<h1 class="site-title logo-title"> <a
	href="http://demos.quadroideas.com/binderpro/" rel="home"> <img
	src="http://cdn.quadroideas.com/binderpro/files/2014/07/logo-binder-pro-web5-e1406763762293.png" alt="Binder PRO" title="Binder PRO Logo"> </a></h1>
</div>
<h2 class="site-description">Welcome to HOTSHOP INSIDE. This is a short description about this site. Enjoy being here!</h2>
<ul class="social-area  brand-color header-social-icons">
	<li><a href="#" target="_self" title="Facebook"><i class="fa fa-facebook"></i></a></li>
	<li><a href="#" target="_self" title="Instagram"><i class="fa fa-instagram"></i></a></li>
	<li><a href="#" target="_self" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
	<li><a href="#" target="_self" title="Twitter"><i class="fa fa-twitter"></i></a></li>

</ul>
<h1 class="menu-toggle"><i class="fa fa-bars"></i></h1>
<nav id="site-navigation" class="main-navigation" role="navigation">
	<div class="inner-nav"> <a class="skip-link screen-reader-text" href="#content">Skip to content</a>
		<div class="menu-main-manu-container">
			<ul id="menu-main-manu" class="menu">
				<li id="menu-item-1997" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1997">
				<%= link_to "Home", posts_path %>
				</li>

				<% Category.all.each do |category|  %>
				<li id="menu-item-1997" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1997">	<%= link_to category.name, posts_path(category: category.name)%> </li>
				<% end %>

<% if user_signed_in? %>
					<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Setting <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
		<li><%= link_to "New Post", new_post_path(@post)%> </li>
		<li>
			<% if user_signed_in? %>

                    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                  <%# else %>
                    <!--li><%#= link_to('Login', new_user_session_path)  %></li-->
                  <% end %>

		</li>
			</ul>
			</li>
			<% else %>
                    <li><%= link_to('Login', new_user_session_path)  %></li>
			<% end %>
		</div>
		<div class="header-search">
			<form role="search" method="get" class="search-form" action="http://demos.quadroideas.com/binderpro/"> 
				<label> <span class="screen-reader-text">Search for:</span> 
				<input type="search" class="search-field" placeholder="" value="" name="s" title="Search for:" /> </label> 
				<input type="submit" class="search-submit" value="Search" />
			</form>
		</div>
		<span class="search-handler"></span>
	</div> 
</nav>
</div>
<div class="header-extras"></div> </header>